### ISSUE TITLE
crash in module on notification

### ISSUE THREAD

**Issue by jfischl** [superfeedr/superfeedr-node#10]
/app/node_modules/superfeedr/lib/superfeedr.js:62
                                    ^
                     var el = entry.getChild(key);
 TypeError: Cannot call method 'getChild' of undefined
     at /app/node_modules/superfeedr/lib/superfeedr.js:62:36
     at Array.forEach (native)
     at Array.forEach (native)
     at /app/node_modules/superfeedr/lib/superfeedr.js:61:79
     at Client.<anonymous> (/app/node_modules/superfeedr/lib/superfeedr.js:58:23)
     at Client.emit (events.js:67:17)
     at Client.onRawStanza (/app/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/client.js:159:14)
     at Client.onStanza (/app/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/connection.js:237:14)
     at Client.emit (events.js:67:17)
     at StreamParser.<anonymous> (/app/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/connection.js:136:14)

**Comment by superfeedr** [comment]
Hum... Do you by any chance have the content of the notification, or at least the feed URL?

**Comment by jfischl** [comment]
I am not sure exactly which one it is. It is likely a facebook feed such as this one though: 
http://www.facebook.com/feeds/page.php?format=atom10&amp;id=34363100821

It might be useful to have some logging in the library. I could fork and add this in using the winston logging library. What do you think?

**Comment by superfeedr** [comment]
That would be amazing :) Please make this library map your needs and I will merge these changes if I think they apply to more people!

**Comment by mattpowell** [comment]
Just ran in to this -- here's the contents of the `notification` object (from line 27 of superfeedr.js) and `psevent` (from line 28 of superfeedr.js):

psevent:

```
{ children: 
   [ '\n',
     '    ',
     { children: 
        [ '\n',
          '      ',
          { children: [ '109511B in 9.619049941s', [length]: 1 ],
            name: 'http',
            parent: [Circular],
            attrs: { code: '200' } },
          '\n',
          '      ',
          { children: [ '2012-08-22T21:39:34Z', [length]: 1 ],
            name: 'next_fetch',
            parent: [Circular],
            attrs: {} },
          '\n',
          '      ',
          { children: [ '0', [length]: 1 ],
            name: 'entries_count_since_last_maintenance',
            parent: [Circular],
            attrs: {} },
          '\n',
          '      ',
          { children: [ '300', [length]: 1 ],
            name: 'period',
            parent: [Circular],
            attrs: {} },
          '\n',
          '      ',
          { children: [ '2012-08-22T21:34:44Z', [length]: 1 ],
            name: 'last_fetch',
            parent: [Circular],
            attrs: {} },
          '\n',
          '      ',
          { children: [ '2009-03-30T22:25:05-04:00', [length]: 1 ],
            name: 'last_parse',
            parent: [Circular],
            attrs: {} },
          '\n',
          '      ',
          { children: [ '2012-08-21T17:33:56-04:00', [length]: 1 ],
            name: 'last_maintenance_at',
            parent: [Circular],
            attrs: {} },
          '\n',
          '      ',
          { children: [ [length]: 0 ],
            name: 'link',
            parent: [Circular],
            attrs: 
             { href: 'http://clientside.cnet.com/feed/',
               type: '',
               title: '',
               rel: 'self' } },
          '\n',
          '    ',
          [length]: 26 ],
       name: 'status',
       parent: [Circular],
       attrs: 
        { xmlns: 'http://superfeedr.com/xmpp-pubsub-ext',
          feed: 'http://clientside.cnet.com/feed/' } },
     '\n',
     '    ',
     { children: 
        [ '\n',
          '      ',
          { children: 
             [ '\n',
               '        ',
               { children: 
                  [ '<',
                    '!DOCTYPE html',
                    '>',
                    ' ',
                    '<',
                    'html lang=',
                    '"',
                    'en',
                    '"',
                    ' xmlns:og=',
                    '"',
                    'http://opengraphprotocol.org/schema/',
                    '"',
                    ' xmlns:fb=',
                    '"',
                    'http://ogp.me/ns/fb#',
                    '"',
                    '>',
                    ' ',
                    '<',
                    '!-- Chewie loves you --',
                    '>',
                    ' ',
                    '<',
                    'head',
                    '>',
                    ' ',
                    '<',
                    '!-- NR header --',
                    '>',
                    ' ',
                    '<',
                    '!-- NEW_RELIC_HEADER_SCRIPT --',
                    '>',
                    ' ',
                    '<',
                    'title',
                    '>',
                    'Product reviews and prices, software downloads, and tech news - CNET',
                    '<',
                    '/title',
                    '>',
                    ' ',
                    '<',
                    'meta http-equiv=',
                    '"',
                    'Content-Type',
                    '"',
                    ' content=',
                    '"',
                    'text/html; charset=utf-8',
                    '"',
                    ' /',
                    '>',
                    ' ',
                    '<',
                    'meta name=',
                    '"',
                    '"',
                    ' http-equiv=',
                    '"',
                    'X-UA-Compatible',
                    '"',
                    ' content=',
                    '"',
                    'IE=edge,chrome=1',
                    '"',
                    ' /',
                    '>',
                    ' ',
                    '<',
                    'meta property=',
                    '"',
                    'fb:app_id',
                    '"',
                    ' content=',
                    '"',
                    '16995676698',
                    '"',
                    '/',
                    '>',
                    '\n',
                    '<',
                    'meta property=',
                    '"',
                    'fb:admins',
                    '"',
                    ' content=',
                    '"',
                    '100001036810388',
                    '"',
                    '/',
                    '>',
                    '\n',
                    '<',
                    'meta property=',
                    '"',
                    'og:site_name',
                    '"',
                    ' content=',
                    '"',
                    'CNET',
                    '"',
                    '/',
                    '>',
                    ' ',
                    '<',
                    '!--[if IE]',
                    '>',
                    '<',
                    '![endif]--',
                    '>',
                    ' ',
                    '<',
                    'link type=',
                    '"',
                    'text/css',
                    '"',
                    ' rel=',
                    '"',
                    'stylesheet',
                    '"',
                    ' href=',
                    '"',
                    'http://asset2.cbsistatic.com/cnwk.1d/css/rb/Build/global/base.css?v=2',
                    '"',
                    '/',
                    '>',
                    ' ',
                    '<',
                    '!--[if gte IE 9]',
                    '>',
                    ' ',
                    '<',
                    'link type=',
                    '"',
                    'text/css',
                    '"',
                    ' rel=',
                    '"',
                    'stylesheet',
                    '"',
                    ' href=',
                    '"',
                    'http://i.i.com.com/cnwk.1d/css/rb/Build/global/ie9.css',
                    '"',
                    '/',
                    '>',
                    ' ',
                    '<',
                    '![endif]--',
                    '>',
                    ' ',
                    '<',
                    '!--[if IE 8]',
                    '>',
                    ' ',
                    '<',
                    'link type=',
                    '"',
                    'text/css',
                    '"',
                    ' rel=',
                    '"',
                    'stylesheet',
                    '"',
                    ' href=',
                    '"',
                    'http://i.i.com.com/cnwk.1d/css/rb/Build/global/ie8.css',
                    '"',
                    '/',
                    '>',
                    ' ',
                    '<',
                    '![endif]--',
                    '>',
                    ' ',
                    '<',
                    '!--[if IE 7]',
                    '>',
                    ' ',
                    '<',
                    'link type=',
                    '"',
                    'text/css',
                    '"',
                    ' rel=',
                    '"',
                    'stylesheet',
                    '"',
                    ' href=',
                    '"',
                    'http://i.i.com.com/cnwk.1d/css/rb/Build/global/ie7.css',
                    '"',
                    '/',
                    '>',
                    ' ',
                    '<',
                    '![endif]--',
                    '>',
                    ' ',
                    '<',
                    '!--[if IE 6]',
                    '>',
                    ' ',
                    '<',
                    'link type=',
                    '"',
                    'text/css',
                    '"',
                    ' rel=',
                    '"',
                    'stylesheet',
                    '"',
                    ' href=',
                    '"',
                    'http://i.i.com.com/cnwk.1d/css/rb/Build/global/ie6.css',
                    '"',
                    '/',
                    '>',
                    ' ',
                    '<',
                    '![endif]--',
                    '>',
                    ' ',
                    '<',
                    'link type=',
                    '"',
                    'text/css',
                    '"',
                    ' rel=',
                    '"',
                    'stylesheet',
                    '"',
                    ' media=',
                    '"',
                    'screen',
                    '"',
                    ' href=',
                    '"',
                    'http://asset3.cbsistatic.com/cnwk.1d/css/rb/Build/global/site1.css',
                    '"',
                    '/',
                    '>',
                    ' ',
                    '<',
                    '!-- UGC Maintenance Mode --',
                    '>',
                    ' ',
                    '<',
                    '!-- ugcFlags Comments mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags Forums mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags Toolbar mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags AssetRating mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags UFO mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags DlUFO mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags Login mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags SocialLogin mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags UserLists mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags UserDB mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags RPS mmode value: false --',
                    '>',
                    '\n',
                    '<',
                    '!-- ugcFlags Global mmode value: false --',
                    '>',
                    ' ',
                    '<',
                    'script type=',
                    '"',
                    'text/javascript',
                    '"',
                    '>',
                    '\n',
                    '    if(navigator.userAgent.match(/ipad/i)){',
                    '\n',
                    '        document.write(',
                    '\'',
                    '<',
                    'lin',
                    [length]: 310 ],
                 name: 'content',
                 parent: [Circular],
                 attrs: 
                  { xmlns: 'http://www.w3.org/2005/Atom',
                    truncated: 'true',
                    type: 'text/html' } },
               '\n',
               '      ',
               [length]: 5 ],
            name: 'item',
            parent: [Circular],
            attrs: { xmlns: 'http://jabber.org/protocol/pubsub' } },
          '\n',
          '    ',
          [length]: 5 ],
       name: 'items',
       parent: [Circular],
       attrs: { node: 'http://clientside.cnet.com/feed/' } },
     '\n',
     '  ',
     [length]: 8 ],
  name: 'event',
  parent: 
   { children: [ '\n', '  ', [Circular], '\n', [length]: 4 ],
     name: 'message',
     parent: null,
     attrs: 
      { 'xmlns:stream': 'http://etherx.jabber.org/streams',
        from: 'firehoser.superfeedr.com',
        to: 'mttpwll@superfeedr.com' } },
  attrs: { xmlns: 'http://jabber.org/protocol/pubsub#event' } }
```

notification:

```
{ entries: [ [length]: 0 ],
  feed: 
   { lastMaintenance: 1345584836000,
     httpStatus: '109511B in 9.619049941s',
     period: 300,
     url: 'http://clientside.cnet.com/feed/',
     nextFetch: 1345671574000,
     httpCode: 200,
     lastParse: 1238466305000,
     title: ';',
     lastFetch: 1345671284000 } }
```

Thanks, and let me know if you need any more info.

**Comment by superfeedr** [comment]
@mattpowell Thanks Matt! actually, I would need the raw data of the notification. Do you think you could provide that if you are able to reproduce the bug?
Thanks,

**Comment by mattpowell** [comment]
Is this what you need: https://gist.github.com/5ece5c632862e2b8c57a ?

Either case, thanks for helping dig in to this!

**Comment by mattpowell** [comment]
One more: https://gist.github.com/ae58e5786e5d1284c400

Seems like superfeedr.js is expecting each notification to have an `item` node with an `entry` child. But these last two notifications had a `content` child instead. Any guesses why that is?

**Comment by superfeedr** [comment]
Yip. That's exactly that. You would only get an `<entry>` element when the content is actually a feed (RSS or Atom). Since we support any kind of arbitrary format, we also sometimes push items that only have a `<content>`... for example in the context of HTML pages.
I'll try to fix that quickly.
