### ISSUE TITLE
Authenticates fine but fails with client.on('connected'...

### ISSUE THREAD

**Issue by lumberbeard** [superfeedr/superfeedr-node#27]
From using basic.js in the example file and putting my own credentials  ("username", "password") it's successfully getting the client (and authenticating) but fails immediately on the client.on('connected', function() part with the below. 

Any ideas?

Error: getaddrinfo EAI_FAIL
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

**Comment by lumberbeard** [comment]
After diving in a little further on this...

It look like it's failing to resolve this:

"_xmpp-client._tcp.gmail.com@superfeedr.com"

once I stopped using the entire email as the username it worked. However, now it's failing on "xmpp.Iq is not a constructor"
