### ISSUE TITLE
Unsupported ssl protocol on node v12

### ISSUE THREAD

**Issue by JimLynchCodes** [superfeedr/superfeedr-node#30]
Hello! I am trying to run code similar to the [example file](https://github.com/superfeedr/superfeedr-node/blob/master/examples/basic.js) with node v12.16.1.

Here is my code: 
```
var Superfeedr = require('superfeedr');

client = new Superfeedr("Eonjim", "[my_actual_password]");
client.on('connected', function () {

    console.log('connected!');
    client.subscribe("http://blog.superfeedr.com/atom.xml", function (err, feed) {
        
          console.log('subscribed!', feed);
    });
});
```

It seems to be successfully connected, but when trying to subscribe to any feed I just get the same error...

Here is the error output I'm seeing:
```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: 4412734912:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1929:

Emitted 'error' event on Client instance at:
    at Client.<anonymous> (/Users/jlynch/Git-Projects/Ameritrader-Bots/news-watcher/node_modules/node-xmpp-client/lib/Client.js:158:23)
    at Connection.emit (events.js:323:22)
    at TLSSocket.onDisconnect (/Users/jlynch/Git-Projects/Ameritrader-Bots/news-watcher/node_modules/reconnect-core/index.js:59:17)
    at TLSSocket.emit (events.js:323:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  library: 'SSL routines',
  function: 'ssl_choose_client_version',
  reason: 'unsupported protocol',
  code: 'ERR_SSL_UNSUPPORTED_PROTOCOL'
}
```

Any thoughts on what I'm doing wrong here? 

Thanks! ♥️

**Comment by JimLynchCodes** [comment]
bump 🙃
