### ISSUE TITLE
tests don't all pass for me

### ISSUE THREAD

**Issue by jfischl** [superfeedr/superfeedr-node#8]
I get an error when I try to run the mocha tests (see below). I also get the same error when I try my own simple test case. It seems that nextFetch, lastFetch and lastParse are undefined and it gaks. 

mocha subscribe.js 

  .

  ✖ 1 of 1 tests failed:

  1) Subscription should call the subscription callback:
     TypeError: Cannot call method 'getText' of undefined
      at Object.14993 (/Users/jason/src/blipboard-server/node_modules/superfeedr/lib/superfeedr.js:108:57)
      at Client.<anonymous> (/Users/jason/src/blipboard-server/node_modules/superfeedr/lib/superfeedr.js:24:43)
      at Client.emit (events.js:67:17)
      at Client.onRawStanza (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/client.js:159:14)
      at Client.emit (events.js:67:17)
      at Client.onStanza (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/connection.js:237:14)
      at StreamParser.<anonymous> (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/connection.js:136:14)
      at StreamParser.emit (events.js:67:17)
      at [object Object].<anonymous> (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/stream_parser.js:42:22)
      at [object Object].emit (events.js:67:17)
      at [object Object].emit (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/node_modules/node-expat/lib/node-expat.js:18:12)
      at [object Object].parse (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/node_modules/node-expat/lib/node-expat.js:24:24)
      at StreamParser.write (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/stream_parser.js:78:26)
      at Client.onData (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/connection.js:184:21)
      at CleartextStream.<anonymous> (/Users/jason/src/blipboard-server/node_modules/superfeedr/node_modules/node-xmpp/lib/xmpp/connection.js:53:14)
      at CleartextStream.emit (events.js:88:20)
      at CleartextStream._push (tls.js:371:12)
      at SecurePair.cycle (tls.js:734:20)
      at EncryptedStream.write (tls.js:130:13)
      at Socket.ondata (stream.js:38:26)
      at Socket.emit (events.js:67:17)
      at TCP.onread (net.js:367:14)

**Comment by superfeedr** [comment]
Let me look into that.

**Comment by superfeedr** [comment]
All fixed :) Enjoy!

**Comment by jfischl** [comment]
Thanks. Works great now.
